apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: "wordpressdb"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "mysqlwordpress/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "mysqlwordpress/data/database/config" -}}
          export MYSQL_USER="{{ .Data.data.MYSQL_USER }}" \
          export MYSQL_PASSWORD="{{ .Data.data.MYSQL_PASSWORD }}" \
          export MYSQL_ROOT_PASSWORD="{{ .Data.data.MYSQL_ROOT_PASSWORD }}" \
          export MYSQL_DATABASE="{{ .Data.data.MYSQL_DATABASE }}"
          {{- end -}}
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      serviceAccountName: wordpressdb
      containers:
        - name: db
          command: ["sh"] 
          args: ['-c', '. /vault/secrets/database-config.txt && env > /vault/secrets/test && tail -f /dev/null']
          image: mysql:5.7
          ports:
            - containerPort: 3306
      restartPolicy: Always
